# Generated by Django 3.0.8 on 2020-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic', '0002_auto_20200714_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
